=== Chinow/Projbook/src/Projbook.Core/Projbook/Core/Model/Configuration/Validation/configuration-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "anyOf": [
    { "required": [ "template-html" ] },
    { "required": [ "template-pdf" ] }
  ],
  "required": [ "title" ],
  "properties": {
    "title": { "type": "string" },
    "template-html": { "type": "string" },
    "template-pdf": { "type": "string" },
    "output-html": { "type": "string" },
    "output-pdf": { "type": "string" },
    "section-title-base": { "type": "integer", "minimum": 0, "exclusiveMinimum": true },
    "pages": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [ "title", "path" ],
        "properties": {
          "title": { "type": "string" },
          "path": { "type": "string" }
        }
      }
    }
  }
}

=== Chinow/Projbook/src/Projbook.Tests/Resources/testConfigAllValues.json
{
  "title": "Test title",
  "template-html": "Resources/FullGeneration/testTemplate.txt",
  "template-pdf": "Resources/FullGeneration/testTemplate-pdf.txt",
  "output-html": "doc.html",
  "output-pdf":  "doc-pdf-input.html",
  "pages": [
    {
      "path": "Resources/FullGeneration/Page/firstPage.md",
      "title": "First page title"
    },
    {
      "path": "Resources/FullGeneration/Page/secondPage.md",
      "title": "Second page title"
    },
    {
      "path": "Resources/FullGeneration/Page/thirdPage.md",
      "title": "Third page title"
    }
  ]
}

=== Chinow/Projbook/src/Projbook.Example/projbook.json
{
  "title": "Sample document",
  "template-html": "template.html",
  "template-pdf": "template-pdf.html",
  "output-html": "documentation.html",
  "output-pdf": "documentation-pdf-input.html",
  "pages": [
    {
      "title": "First page",
      "path": "Page/page1.md"
    },
    {
      "title": "Second page",
      "path": "Page/page2.md"
    }
  ]
}

=== Chinow/Projbook/src/Projbook.Tests/Resources/Config/AllValues.json
{
  "title": "Test title",
  "template-html": "Template/Template.txt",
  "template-pdf": "Template/Template-pdf.txt",
  "output-html": "doc.html",
  "output-pdf": "doc-pdf-input.html",
  "pages": [
    {
      "path": "Page/Content.md",
      "title": "First page title"
    },
    {
      "path": "Page/Snippet.md",
      "title": "Second page title"
    },
    {
      "path": "Page/Table.md",
      "title": "Third page title"
    }
  ]
}
