=== Chinow/Projbook/src/Projbook.Core/Projbook/Core/Model/Configuration/Validation/index-configuration.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "required": [ "template" ],
  "properties": {
    "title": { "type": "string" },
    "description": { "type": "string" },
    "template": { "type": "string" },
    "output": { "type": "string" },
    "icon": { "type": "string" },
    "configurations": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "anyOf": [
          { "required": [ "template-html" ] },
          { "required": [ "template-pdf" ] }
        ],
        "required": [ "title" ],
        "properties": {
          "title": { "type": "string" },
          "template-html": { "type": "string" },
          "template-pdf": { "type": "string" },
          "output-html": { "type": "string" },
          "output-pdf": { "type": "string" },
          "section-title-base": {
            "type": "integer",
            "minimum": 0,
            "exclusiveMinimum": true
          },
          "pages": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "required": [ "title", "path" ],
              "properties": {
                "title": { "type": "string" },
                "path": { "type": "string" }
              }
            }
          }
        }
      }
    }
  }
}

=== Chinow/Projbook/src/Projbook.Tests/Resources/Config/WithIndex.json
{
  "title": "Index title",
  "description": "Index description",
  "template": "Template/IndexTemplate.txt",
  "output": "index.html",
  "icon": "index-icon.png",
  "configurations": [
    {
      "title": "Test title",
      "description": "Test description",
      "icon": "icon.png",
      "template-html": "Template/Template.txt",
      "template-pdf": "Template/Template-pdf.txt",
      "output-html": "doc.html",
      "output-pdf": "doc-pdf-input.html",
      "pages": [
        {
          "path": "Page/Content.md",
          "title": "First page title"
        },
        {
          "path": "Page/Snippet.md",
          "title": "Second page title"
        },
        {
          "path": "Page/Table.md",
          "title": "Third page title"
        }
      ]
    }
  ]
}

=== Chinow/Projbook/src/Projbook.Documentation/projbook.json
{
  "title": "Projbook",
  "description": "A kick-ass documentation generator!",
  "template": "index-template.html",
  "output": "index.html",
  "icon": "https://raw.githubusercontent.com/defrancea/Projbook/master/resources/Projbook.png",
  "configurations": [
    {
      "title": "Projbook",
      "description": "Main documentation",
      "icon": "https://raw.githubusercontent.com/defrancea/Projbook/master/resources/Projbook.png",
      "template-html": "template.html",
      "output-html": "projbook.html",
      "template-pdf": "template-pdf.html",
      "output-pdf": "projbook-pdf.html",
      "section-title-base": 1,
      "pages": [
        {
          "title": "Jump start",
          "path": "Page/jumpstart.md"
        },
        {
          "title": "Template",
          "path": "Page/template.md"
        },
        {
          "title": "Reference",
          "path": "Page/reference.md"
        }
      ]
    }
  ]
}
